###
# @name Add message
POST http://localhost:3000/message
Content-Type: application/json
Accept: application/json

{
  "object": "Perquisition",
  "content": "Bonjour, vous serez perquisitionnez demain",
  "idlist": 1,
  "idmodel": 6,
  "idstate": 2
}

###
# @name Get all messages
GET http://localhost:3000/message
Accept: application/json

###
# @name Update message
PUT http://localhost:3000/message
Accept: application/json
Content-Type: application/json

{
  "idmessage": 9,
  "object": "Hello",
  "content": "Bonjour, vous serez perquisitionnez demain",
  "sentDate": "2022-05-22",
  "sentHour": "15:25",
  "idlist": 1,
  "idmodel": 1,
  "idstate": 2
}

###
# @name Delete message
DELETE http://localhost:3000/message/4
Accept: application/json
